[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "agonzlaez"
authors = [{name = "Chinchin", email = "https://www.pagochinchin.com/"}]
dynamic = ["version", "description"]
